# .streamlit/secrets.toml
[auth]
cookie_name = "mon_app_cookie"
cookie_key = "une_clé_secrète"
cookie_expiry_days = 30

[users]
name = "Xavier LASSUS"
email = "xavier@example.com"
password = "$2b$12$uZrH/WOOSo6dcDWGU.2ZCurqX4AceteagOMTujP96P79oJ3QeS3xy"  # mot de passe haché
