# .streamlit/secrets.toml
[auth]
cookie_name = "mon_app_cookie"
cookie_key = "une_clé_secrète"
cookie_expiry_days = 30

[users]
name = "Xavier"
email = "xavier@email.com"
password = "$2b$12$4pKQ8YkWq6c7W8fW1Kx4QO3m8H8b1LJz12vQJQWc59O8v8lbI9rQK"
